version: '3'
services:
  db:
    image: postgres:13
    env_file: .env  # load from envs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env  # load from envs
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
